#ifndef INCLUDE_TOKENS
#define INCLUDE_TOKENS

#include <stdint.h>

#define MAX_TOKENS 256

#define IS_NUMERIC(ch) ((ch) >= '0' && (ch) <= '9')
#define IS_ALPHA(ch) \
    (((ch) >= 'a' && (ch) <= 'z') || ((ch) >= 'A' && (ch) <= 'Z'))

typedef enum {
  TOK_NONE,

  // Those tokens require further processing
  // - -> -= --
  // + ++ +=
  // < << <= <<=
  // > >> >= >>=
  // = ==
  // ! !=
  // & && &=
  // * *=
  // / /=
  // % %=
  // ^ ^=
  // | || |=
  TOK_MINUS, TOK_PLUS, TOK_LT, TOK_GT,
  TOK_EQ, TOK_NOT, TOK_AND, TOK_STAR,
  TOK_SLASH, TOK_PERCENT, TOK_HAT, TOK_OR,

  TOK_ARROW, TOK_MINUS_EQ, TOK_DMINUS, TOK_DPLUS,
  TOK_PLUS_EQ, TOK_LSFT, TOK_LE, TOK_LSFT_EQ, 
  TOK_RSFT, TOK_GE, TOK_RSF_EQ, TOK_DEQ, 
  TOK_NEQ, TOK_DAND, TOK_AND_EQ, TOK_STAR_EQ,
  TOK_SLASH_EQ, TOK_PERCENT_EQ, TOK_HAT_EQ, TOK_DOR,
  TOK_OR_EQ,

  TOK_DOT, TOK_TILDA, TOK_COLON, TOK_SEMICOLON,
  TOK_COMMA, TOK_LPAREN, TOK_RPAREN, TOK_LBRACE,
  TOK_RBRACE, TOK_LSQUARE, TOK_RSQUARE, TOK_QUESTION,

  TOK_IDENT,
  TOK_DECIMAL,

#define KEYWORDS_START TOK_BREAK
  // Other keywords
  TOK_BREAK, TOK_FOR, TOK_WHILE, TOK_GOTO, TOK_SIZEOF,
  TOK_CONTINUE, TOK_IF, TOK_DEFAULT, TOK_IMAGINARY, TOK_DO,
  TOK_RETURN, TOK_CASE,

#define DECL_SPEC_START TOK_AUTO
  // Declaration specifiers
  TOK_AUTO, TOK_ENUM, TOK_RESTRICT, TOK_UNSIGNED, TOK_EXTERN,
  TOK_FLOAT, TOK_SHORT, TOK_VOLATILE, TOK_CHAR, TOK_VOID,
  TOK_SIGNED, TOK_CONST, TOK_BOOL, TOK_STATIC, TOK_COMPLEX,
  TOK_INLINE, TOK_STRUCT, TOK_INT, TOK_REGISTER, TOK_UNION,
  TOK_SWITCH, TOK_DOUBLE, TOK_LONG, TOK_TYPEDEF, TOK_ELSE,

  TOK_COUNT,
} TokenType;

// TODO: tokens have been reordered, fix it
const char *TOKEN_TYPE_STR[TOK_COUNT] = {
  "TOK_NONE",

  "TOK_MINUS", "TOK_PLUS", "TOK_LT", "TOK_GT",
  "TOK_EQ", "TOK_NOT", "TOK_AND", "TOK_STAR",
  "TOK_SLASH", "TOK_PERCENT", "TOK_HAT", "TOK_OR",

  "TOK_ARROW", "TOK_MINUS_EQ", "TOK_DMINUS", "TOK_DPLUS",
  "TOK_PLUS_EQ", "TOK_LSFT", "TOK_LE", "TOK_LSFT_EQ",
  "TOK_RSFT", "TOK_GE", "TOK_RSF_EQ", "TOK_DEQ",
  "TOK_NEQ", "TOK_DAND", "TOK_AND_EQ", "TOK_STAR_EQ",
  "TOK_SLASH_EQ", "TOK_PERCENT_EQ", "TOK_HAT_EQ", "TOK_DOR",
  "TOK_OR_EQ",

  "TOK_DOT", "TOK_TILDA", "TOK_COLON", "TOK_SEMICOLON",
  "TOK_COMMA", "TOK_LPAREN", "TOK_RPAREN", "TOK_LBRACE",
  "TOK_RBRACE", "TOK_LSQUARE", "TOK_RSQUARE", "TOK_QUESTION",

  "TOK_IDENT",
  "TOK_DECIMAL",

  "TOK_BREAK", "TOK_FOR", "TOK_WHILE", "TOK_GOTO", "TOK_SIZEOF",
  "TOK_CONTINUE", "TOK_IF", "TOK_DEFAULT", "TOK_IMAGINARY", "TOK_DO",
  "TOK_RETURN", "TOK_CASE",

  "TOK_AUTO", "TOK_ENUM", "TOK_RESTRICT", "TOK_UNSIGNED", "TOK_EXTERN",
  "TOK_FLOAT", "TOK_SHORT", "TOK_VOLATILE", "TOK_CHAR", "TOK_VOID",
  "TOK_SIGNED", "TOK_CONST", "TOK_BOOL", "TOK_STATIC", "TOK_COMPLEX",
  "TOK_INLINE", "TOK_STRUCT", "TOK_INT", "TOK_REGISTER", "TOK_UNION",
  "TOK_SWITCH", "TOK_DOUBLE", "TOK_LONG", "TOK_TYPEDEF", "TOK_ELSE",
};

typedef struct {
  TokenType type;
  uint16_t len;
  uint32_t start;
} Token;

void tokenize(const char *source, Token tokens_out[MAX_TOKENS]);
void print_tokens(const Token *tokens);

#endif

